reloadMsg: '&aReloading Config!'
NoPermMsg: '&cYou have perm using that command!'
SwearList:
  - 'Fuck'
  - 'Dick'
  - 'Pussy'
  - 'Gay'
  - 'Bitch'
  - 'Fucking'
  - 'Mother fucker'
  - 'Vagina'
  - 'Sex'
  - 'Cunt'
  - 'Bastard'
  - 'Slut'
  - 'Whore'
  - 'Idiot'